---
- name: manage_ssh_keys | checking for ssh pub keys if defined
  stat: path={{ item[1] }}
  register: ssh_pub_keys
  delegate_to: localhost
  run_once: true
  sudo: false
  with_subelements:
    - deploy_ssh_pub_keys
    - keys
  when: (manage_ssh_keys is defined and (item[1] is defined and item[1] != '' and item[1] != none))

- name: manage_ssh_keys | adding ssh user keys
  authorized_key: user={{ item[0].remote_user }} key="{{ lookup('file', 'item[1]') }}" state=present
  with_subelements:
    - deploy_ssh_pub_keys
    - keys
  when: (ssh_pub_keys.results[0].stat.exists and item[1] is defined and (item[1] != '' and item[1] != none))
