---
- name: manage_ssh_keys | adding ssh user keys
  authorized_key:
    user: "{{ item.0.remote_user }}"
    key: "{{ lookup('file', item.1) }}"
    state: present
  with_subelements:
    - manage_ssh_keys
    - keys
  when: >
        (item.0.present is defined and item.0.present) and
        item.1 is defined

- name: manage_ssh_keys | removing ssh user keys
  authorized_key:
    user: "{{ item.0.remote_user }}"
    key: "{{ lookup('file', item.1) }}"
    state: absent
  with_subelements:
    - manage_ssh_keys
    - keys
  when: >
        (item.0.present is defined and not item.0.present) and
        item.1 is defined

